server:
  port: 8010


logging:
  level:
    root：TRACE

user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: microservce-service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
