server:
  port: 8010


logging:
  level:
    root：TRACE

user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: microservce-service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/

  instance:
    prefer-ip-address: true
    metadata-map:
      # 测试元数据
      test-metadata: first mircroservice

# 改变负载均衡的规则（一般情况下不需要改变）
microservce-service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
