spring:
  application:
    name: microservce-service-eureka
  profiles:
    active: peer1


#eureka:
#  server:
#    enable-self-preservation: false

# 开启安全访问

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

---
spring:
  # 指定profile=peer1
  profiles: peer1

server:
  port: 8761

eureka:
  client:
    registerWithEureak: false
    fetchRegistry: false
    service-url:
      #defaultZone: http://peer2:8762/eureka/
      defaultZone: http://admin:admin@peer2:8762/eureka/ #安全访问
  instance:
    prefer-ip-address: true
    hostname: peer1

---
spring:
  # 指定profile=peer2
  profiles: peer2

server:
  port: 8762

eureka:
  client:
    registerWithEureak: false
    fetchRegistry: false
    service-url:
      #defaultZone: http://peer1:8761/eureka/
      defaultZone: http://admin:admin@peer1:8761/eureka/ #安全访问
  instance:
    prefer-ip-address: true
    hostname: peer2


